
version: '2'

services:
  master:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        HOST: master
    expose:
      - 5432
    links:
      - standby
    env_file: ./master.env
    environment:
      - HOST=master
    networks:
      postgresnet:
        ipv4_address: 172.25.0.2

  standby:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        HOST: standby
    expose:
      - 5432
    env_file: ./standby.env
    environment:
      - HOST=standby
    networks:
      postgresnet:
        ipv4_address: 172.25.0.3

networks:
  postgresnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24